spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3306/batch?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        schema: classpath:/org/springframework/batch/core/schema-mysql.sql
        username: root
        password: root
        
    batch:
        # 关闭自动执行，需要用户手动发送请求
        initialize-schema: always
        job:
            enabled: false

