spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3306/jpa?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        username: root
        password: root

    jpa:
        show-sql: true
        database: mysql
        hibernate:
            ddl-auto: update    
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL57Dialect
        